set(TY_CONFIG_PACKAGE_NAME "triChecked Updater" CACHE STRING "")

set(TY_CONFIG_TYC_BUILD OFF CACHE BOOL "")
set(TY_CONFIG_TYQT_BUILD OFF CACHE BOOL "")

set(TY_CONFIG_UPTY_EXECUTABLE "triChecked Updater" CACHE STRING "")
set(TY_CONFIG_UPTY_NAME "triChecked Updater" CACHE STRING "")

set(TY_CONFIG_URL_WEBSITE "http://trichecked.de/" CACHE STRING "")
set(TY_CONFIG_URL_BUGS "" CACHE STRING "")
